---
title: "COVID-19 Questions"
author: "Ada"
date: "October 30, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1. How many on-site interviews were moved to remote? Q114
  + Differences in institution type?
  + Did this impact offers received?
  + Did this impact the likelihood to reject an offer for any reason?

2. How many offers were rescinded due to covid? Q115 -- See `get_rescinded_demos.R`
  + ~~Differences in institution type?~~ 
  + Demographic differences?
    + Gender
    + Racial Minority
    + Academic Field
    + ~~Geographic location (not sure if can pull this, I think we only had them put who they got offers from)~~
    + Position (PhD, postdoc, other)
    
3. Did applicants alter their strategy? Q116 + follow up survey
  + Differences in institution type?
  + Demographic differences?
    +Gender
    +Racial Minority
    +Academic Field
    +Position (PhD, postdoc, other)
    
4. Did applicants reject offers because of Covid? -- See `get_rejected_demos.R`
  + % of overall rejections
  + Differences in institution type?
  + Demographic differences?
      + Gender - caregiving? kids?
      + Racial Minority
      + Academic Field
      + Position (PhD, postdoc, other)

5. In response to Q52 (How did you respond to any offers received? Please check all that apply.), if participant checked:
  + I rejected offer(s) because of reduced resources directly related to the economic impact of Covid-19
OR
  + I rejected offer(s) because of other reasons pertaining to the impact of Covid-19
    + Are they more likely to be in a certain demographic group?
    + Are reported combined household incomes (Q21) lower in those selecting these responses than in those who do not?
    + Are they more likely to have children or other dependents in their household (Q18)?
    + Are they more likely to be first-generation college/PhD students (Q15, Q16)?
    + Are they more likely to NOT reside in the US (Q14)?
    + Are they more likely to be female (Q7) or from a certain ethnic group (Q10)?
